version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  publish-packages-npm:
    <<: *defaults
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Validate npm authentication
          command: npm whoami

workflows:
  version: 2

  verify-test-build:
    jobs:
      - publish-packages-npm
